[build]
base = "/"
publish = "out/"
command = "npm run export"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "netlify-plugin-env"
	[plugins.inputs]
	mode = 'suffix'

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=31536000,
	no-cache,
	no-store,
	must-revalidate'''